# Generated by Django 2.2.25 on 2021-12-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entrt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrt',
            new_name='Entry',
        ),
    ]
